### ISSUE TITLE
Select zone?

### ISSUE THREAD

**Issue by DangerD1024** [Hypfer/lovelace-valetudo-map-card#105]
Is there any way to select zone/custom using this plugin?

**Comment by TheLastProject** [comment]
Not yet, I would happily accept a patch for it but nobody bothered to implement it.

**Comment by t0bse** [comment]
any news on this? i'm coming from the xiaomi map card and used to select the zone
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card

**Comment by Hypfer** [comment]
I really don't see the point in reimplementing the same functionality that the Valetudo WebInterface provides a second time but this time it is a tiny square embedded in some other Webapplication that comes with a ton of constrains.

This card provides the Map as a small rectangle with a few buttons that do predefined actions below. That's IMO the only thing that makes sense from an UX perspective.

If you want to do more than that, you should not be doing so through a lovelace card.
Home-Assistant named them Dashboards after all. They're made for quick glances and interactions and not fiddly tiny rectangle drawing.

Instead, what about adding the Valetudo WebInterface as an iFrame to the sidebar?
This way, it is also sorta part of Home Assistant and quickly accessible in e.g. the Home Assistant app or a wall mounted tablet, however it is also its own thing with much more screen real estate available to do advanced things.

**Comment by DangerD1024** [comment]
> any news on this? i'm coming from the xiaomi map card and used to select the zone https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card

![Screenshot_20221005-093000](https://user-images.githubusercontent.com/4560434/193995550-b427ac3b-d20e-43e9-9161-62be438983a7.png)
Only this way, look at block before, you can select zone by saved ID and startc vacuum cleaner
