### ISSUE TITLE
Map card is not available in card list but is functional if manually added in YAML

### ISSUE THREAD

**Issue by mill1000** [Hypfer/lovelace-valetudo-map-card#133]
Home Assistant Version: 2022.12.3 - Docker
Valetudo Map Card Version: 2022.01.2
Valetudo Version: 2022.11.0
Install Method: HACS v1.29.0

Cache Cleared: Yes. Also tried private browsing.
Following the guide [here](https://hass.valetudo.cloud/) the Valetudo Map Card does not appear to be available when clicking the Add Card button.
![image](https://user-images.githubusercontent.com/6924622/209061087-9aeaa714-122c-468f-93f7-adf6fe4b555f.png)

However, the card is functional if manually defined via YAML.
![image](https://user-images.githubusercontent.com/6924622/209061157-ba5ce724-4fb2-4a99-9419-a096f687f720.png)

**Comment by Hypfer** [comment]
Oh wow you're completely right.

I did implement the card picker support back in July https://github.com/Hypfer/lovelace-valetudo-map-card/commit/e2f85676e6cfbd6e0756afda4bdc645c77e8bc74 but apparently it was never merged to the master branch.

As you see, cleaning up the repo is still on my to-do list. Sorry about that.

Anyway, I've just merged that and also created a new release. If this doesn't solve the issue please let me know.
I'm also a bit confused that no one else has reported that so far

**Comment by mill1000** [comment]
Worked like a charm. Thanks for the quick response!
