### ISSUE TITLE
Smooth travel path

### ISSUE THREAD

**Issue by matt8707** [Hypfer/lovelace-valetudo-map-card#31]
Minor issue. Would it be possible to smooth the path of the vacuum icon travel? I know we're getting the data from mqtt but there must be some way to ease the transition so it's less twitchy. Thanks for a great card!

**Comment by TheLastProject** [comment]
I'm sure it's technically possible, but it will need some serious refactoring. Right now, I just redraw the whole map from scratch every time things change, which obviously makes things like this impossible.

**Comment by matt8707** [comment]
Yeah, that's more work than I thought. Thanks for answering.
